In [1]:
import pandas as pd

# Carregar o arquivo Excel
df = pd.read_excel("churn.xlsx")

# Mostrar as primeiras linhas
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7569-NMZYQ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),118.75,8672.45,No
1,8984-HPEMB,Female,0,No,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.65,8477.60,No
2,5989-AXPUC,Female,0,Yes,No,68,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Mailed check,118.60,7990.05,No
3,5734-EJKXG,Female,0,No,No,61,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,118.60,7365.70,No
4,8199-ZLLSA,Male,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),118.35,7804.15,Yes

In [2]:
# Verificando o tamanho e o formato dos dados
print("Formato do dataset (linhas, colunas):", df.shape)

# Verificando os tipos de dados
print("\nTipos de dados por coluna:\n")
print(df.dtypes)

# Verificando se existem valores ausentes
print("\nValores nulos por coluna:\n")
print(df.isnull().sum())

# Verificando valores Ãºnicos na variÃ¡vel alvo
print("\nDistribuiÃ§Ã£o da variÃ¡vel alvo (Churn):")
print(df['Churn'].value_counts())

# Percentual de churn vs nÃ£o churn
print("\nPercentual:")
print(df['Churn'].value_counts(normalize=True) * 100)

# Ver algumas estatÃ­sticas numÃ©ricas (exclui colunas categÃ³ricas automaticamente)
print("\nEstatÃ­sticas descritivas:")
print(df.describe())

Formato do dataset (linhas, colunas): (7043, 21)

Tipos de dados por coluna:

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

Valores nulos por coluna:

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

DistribuiÃ§Ã£o da variÃ¡vel alvo (Churn):
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Percentual:
Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

EstatÃ­sticas descritivas:
       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [3]:
# Verificando valores nulos novamente
print("Valores nulos em TotalCharges:", df['TotalCharges'].isnull().sum())

# Exibindo as linhas com valores nulos em TotalCharges
print("\nLinhas com TotalCharges nulo:")
print(df[df['TotalCharges'].isnull()])

# Vamos remover essas linhas, pois sÃ£o poucas (11 de 7043)
df = df.dropna(subset=['TotalCharges'])

# Resetar os Ã­ndices depois da remoÃ§Ã£o
df.reset_index(drop=True, inplace=True)

# Remover colunas irrelevantes para anÃ¡lise
df.drop(columns=['customerID'], inplace=True)

# Verificar se ainda tem valores vazios ou nulos
print("\nValores nulos apÃ³s a limpeza:")
print(df.isnull().sum())

Valores nulos em TotalCharges: 11

Linhas com TotalCharges nulo:
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
2531  5709-LVOEQ  Female              0     Yes        Yes       0
3343  4075-WKNIU  Female              0     Yes        Yes       0
4023  2775-SEFEE    Male              0      No        Yes       0
4315  1371-DWPAZ  Female              0     Yes        Yes       0
4583  4472-LVYGI  Female              0     Yes        Yes       0
5484  4367-NUYAO    Male              0     Yes        Yes       0
5549  3213-VVOLG    Male              0     Yes        Yes       0
6213  3115-CZMZD    Male              0      No        Yes       0
6429  2520-SGTTA  Female              0     Yes        Yes       0
6562  7644-OMVMY    Male              0     Yes        Yes       0
6682  2923-ARZLG    Male              0     Yes        Yes       0

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
2531          Yes                No             DSL                  Yes  ...
3343          Yes               Yes             DSL                   No  ...
4023          Yes               Yes             DSL                  Yes  ...
4315           No  No phone service             DSL                  Yes  ...
4583           No  No phone service             DSL                  Yes  ...
5484          Yes               Yes              No  No internet service  ...
5549          Yes               Yes              No  No internet service  ...
6213          Yes                No              No  No internet service  ...
6429          Yes                No              No  No internet service  ...
6562          Yes                No              No  No internet service  ...
6682          Yes                No              No  No internet service  ...

         DeviceProtection          TechSupport          StreamingTV  \
2531                  Yes                   No                  Yes
3343                  Yes                  Yes                  Yes
4023                   No                  Yes                   No
4315                  Yes                  Yes                  Yes
4583                  Yes                  Yes                  Yes
5484  No internet service  No internet service  No internet service
5549  No internet service  No internet service  No internet service
6213  No internet service  No internet service  No internet service
6429  No internet service  No internet service  No internet service
6562  No internet service  No internet service  No internet service
6682  No internet service  No internet service  No internet service

          StreamingMovies  Contract PaperlessBilling  \
2531                  Yes  Two year               No
3343                   No  Two year               No
4023                   No  Two year              Yes
4315                   No  Two year               No
4583                   No  Two year              Yes
5484  No internet service  Two year               No
5549  No internet service  Two year               No
6213  No internet service  Two year               No
6429  No internet service  Two year               No
6562  No internet service  Two year               No
6682  No internet service  One year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges  Churn
2531               Mailed check          80.85           NaN     No
3343               Mailed check          73.35           NaN     No
4023  Bank transfer (automatic)          61.90           NaN     No
4315    Credit card (automatic)          56.05           NaN     No
4583  Bank transfer (automatic)          52.55           NaN     No
5484               Mailed check          25.75           NaN     No
5549               Mailed check          25.35           NaN     No
6213               Mailed check          20.25           NaN     No
6429               Mailed check          20.00           NaN     No
6562               Mailed check          19.85           NaN     No
6682               Mailed check          19.70           NaN     No

[11 rows x 21 columns]

Valores nulos apÃ³s a limpeza:
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder

# Criar uma cÃ³pia do dataframe
df_model = df.copy()

# Codificando a variÃ¡vel alvo (Churn: Yes -> 1, No -> 0)
df_model['Churn'] = df_model['Churn'].map({'Yes': 1, 'No': 0})

# Codificando todas as variÃ¡veis categÃ³ricas restantes com LabelEncoder
le = LabelEncoder()
for col in df_model.select_dtypes(include=['object']).columns:
    df_model[col] = le.fit_

AttributeError: 'LabelEncoder' object has no attribute 'fit_'

In [5]:
from sklearn.preprocessing import LabelEncoder

# Criar uma cÃ³pia do dataframe
df_model = df.copy()

# Codificando a variÃ¡vel alvo (Churn: Yes -> 1, No -> 0)
df_model['Churn'] = df_model['Churn'].map({'Yes': 1, 'No': 0})

# Codificando todas as variÃ¡veis categÃ³ricas restantes com LabelEncoder
le = LabelEncoder()
for col in df_model.select_dtypes(include=['object']).columns:
    df_model[col] = le.fit_transform(df_model[col])

# Separando X (variÃ¡veis independentes) e y (variÃ¡vel alvo)
X = df_model.drop(columns=['Churn'])
y = df_model['Churn']

# Mostrando uma amostra dos dados codificados
print("Exemplo dos dados tratados:")
print(X.head())

print("\nVariÃ¡vel alvo:")
print(y.head())

Exemplo dos dados tratados:
   gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           1      72             1
1       0              0        0           0      71             1
2       0              0        1           0      68             1
3       0              0        0           0      61             1
4       1              0        0           0      67             1

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              2                1               2             2
1              2                1               2             2
2              2                1               2             2
3              2                1               2             2
4              2                1               2             2

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 2            2            2                2         2
1                 2            2            2                2         2
2                 2            2            2                2         2
3                 2            2            2                2         1
4                 2            2            2                2         1

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges
0                 1              0          118.75       8672.45
1                 1              2          118.65       8477.60
2                 0              3          118.60       7990.05
3                 1              2          118.60       7365.70
4                 1              0          118.35       7804.15

VariÃ¡vel alvo:
0    0
1    0
2    0
3    0
4    1
Name: Churn, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Dividindo os dados em treino e teste (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criando e treinando o modelo de RegressÃ£o LogÃ­stica
model_log = LogisticRegression(max_iter=1000)
model_log.fit(X_train, y_train)

# Fazendo previsÃµes
y_pred_log = model_log.predict(X_test)

# Avaliando o modelo
print("ðŸ”Ž AcurÃ¡cia da RegressÃ£o LogÃ­stica:", accuracy_score(y_test, y_pred_log))
print("\nðŸ“Š Matriz de ConfusÃ£o:")
print(confusion_matrix(y_test, y_pred_log))

print("\nðŸ“‹ RelatÃ³rio de ClassificaÃ§Ã£o:")
print(classification_report(y_test, y_pred_log))

ðŸ”Ž AcurÃ¡cia da RegressÃ£o LogÃ­stica: 0.7860696517412935

ðŸ“Š Matriz de ConfusÃ£o:
[[895 132]
 [169 211]]

ðŸ“‹ RelatÃ³rio de ClassificaÃ§Ã£o:
              precision    recall  f1-score   support

           0       0.84      0.87      0.86      1027
           1       0.62      0.56      0.58       380

    accuracy                           0.79      1407
   macro avg       0.73      0.71      0.72      1407
weighted avg       0.78      0.79      0.78      1407